twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_version: '1.0.0'
        default_results_per_page: '%default_results_per_page%'

when@test:
    twig:
        strict_variables: true
